routes/web.php
<?php

use App\Http\Controllers\ConfigurationController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\MarketingMaterialController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\OrderInvoiceController;
use App\Http\Controllers\PlaceOrderController;
use App\Http\Controllers\PricingController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\StorageController;
use App\Http\Controllers\TrackOrderController;
use App\Http\Controllers\TransferMarginController;
use App\Http\Controllers\TransferMethodController;
use App\Http\Controllers\UserManagementController;
use App\Http\Middleware\AdminMiddleware;
use App\Http\Middleware\MustHaveProfile;
use Illuminate\Auth\Middleware\Authenticate;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', '/track-order')->name('home');
Route::get('/place-order', [PlaceOrderController::class, 'create'])->name('place-order');
Route::post('/place-order', [PlaceOrderController::class, 'store'])->name('place-order');
Route::get('/track-order', [TrackOrderController::class, 'index'])->name('track-order');

Route::post('/order-managements/{order}/images', [OrderController::class, 'storeImage'])->name('order-managements.store-image');
Route::delete('/order-managements/{order}/images/{image}', [OrderController::class, 'deleteImage'])->name('order-managements.delete-image');
Route::put('/order-managements/{order}/designs/{design}/approve', [OrderController::class, 'approveDesign'])->name('order-managements.approve-design');
Route::post('/order-managements/{order}/designs/{design}/revise', [OrderController::class, 'reviseDesign'])->name('order-managements.revise-design');
Route::post('/order-managements/{order}/designs/{design}/revise/{revision}/attachment', [OrderController::class, 'storeReviseAttachment'])->name('order-managements.revise-design.store-attachment');

Route::put('/order-managements/{order}/fix-order', [OrderController::class, 'fixOrder'])->name('order-managements.fix-order');
Route::put('/order-managements/{order}/shipping-data', [OrderController::class, 'saveShippingData'])->name('order-managements.shipping-data');
Route::post('/order-managements/{order}/upload-delivery-receipt', [OrderController::class, 'uploadDeliveryReceipt'])->name('order-managements.upload-delivery-receipt');

Route::get('/order-invoice/{invoice:number}', [OrderInvoiceController::class, 'show'])->name('order-invoice.show');
Route::post('/order-invoice/{invoice:number}/paid', [OrderInvoiceController::class, 'paid'])->name('order-invoice.paid');
Route::put('/order-invoice/{invoice:number}/reset', [OrderInvoiceController::class, 'reset'])->name('order-invoice.reset');
Route::get('/order-invoice/{invoice:number}/print', [OrderInvoiceController::class, 'print'])->name('order-invoice.print');

Route::middleware([Authenticate::class])->group(function () {
    ////////////// DASHBOARD ///////////////
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard')->middleware(MustHaveProfile::class);

    Route::get('/profile', [ProfileController::class, 'index'])->name('profile');
    Route::put('/profile', [ProfileController::class, 'updateAccount'])->name('profile.update-account');
    Route::post('/profile', [ProfileController::class, 'updateProfile'])->name('profile.update-profile');

    ////////////// USER MANAGEMENTS ///////////////
    Route::middleware([AdminMiddleware::class])->group(function () {
        Route::get('/configurations', [ConfigurationController::class, 'index'])->name('configurations');
        Route::put('/configurations', [ConfigurationController::class, 'update'])->name('configurations');
        Route::delete('/configurations', [ConfigurationController::class, 'reset'])->name('configurations');

        Route::post('/transfer-methods', [TransferMethodController::class, 'store'])->name('transfer-methods.store');
        Route::delete('/transfer-methods/{bank}', [TransferMethodController::class, 'delete'])->name('transfer-methods.delete');

        Route::get('/user-managements', [UserManagementController::class, 'index'])->name('user-managements.index');
        Route::get('/user-managements/create', [UserManagementController::class, 'create'])->name('user-managements.create');
        Route::post('/user-managements/store', [UserManagementController::class, 'store'])->name('user-managements.store');
        Route::get('/user-managements/{user}', [UserManagementController::class, 'show'])->name('user-managements.show');
        Route::post('/user-managements/{user}/profile', [UserManagementController::class, 'updateProfile'])->name('user-managements.update-profile');
        Route::put('/user-managements/{user}/verify', [UserManagementController::class, 'verify'])->name('user-managements.verify');
        Route::get('/user-managements/{user}/edit', [UserManagementController::class, 'edit'])->name('user-managements.edit');
        Route::put('/user-managements/{user}', [UserManagementController::class, 'update'])->name('user-managements.update');
        Route::delete('/user-managements/{user}', [UserManagementController::class, 'delete'])->name('user-managements.delete');

        Route::get('/pricings', [PricingController::class, 'index'])->name('pricings.index');
        Route::get('/pricings/create', [PricingController::class, 'create'])->name('pricings.create');
        Route::post('/pricings', [PricingController::class, 'store'])->name('pricings.store');
        Route::get('/pricings/{pricing}', [PricingController::class, 'edit'])->name('pricings.edit');
        Route::delete('/pricings/{pricing}', [PricingController::class, 'destroy'])->name('pricings.destroy');
    });

    Route::put('/user-managements/{user}/bank-account', [UserManagementController::class, 'updateBankAccount'])->name('user-managements.bank-account');

    ////////////// ORDER MANAGEMENTS ///////////////
    Route::get('/order-managements', [OrderController::class, 'index'])->name('order-managements.index');
    Route::get('/order-managements/create', [OrderController::class, 'create'])->name('order-managements.create');
    Route::post('/order-managements', [OrderController::class, 'store'])->name('order-managements.store');

    Route::get('/order-managements/{order}', [OrderController::class, 'show'])->name('order-managements.show');

    Route::get('/order-managements/{order}/edit', [OrderController::class, 'edit'])->name('order-managements.edit');
    Route::put('/order-managements/{order}/update', [OrderController::class, 'update'])->name('order-managements.update');
    
    Route::delete('/order-managements/{order}/archive', [OrderController::class, 'archive'])->name('order-managements.archive');
    Route::put('/order-managements/{order}/process', [OrderController::class, 'process'])->name('order-managements.process');

    Route::post('/order-managements/{order}/designs', [OrderController::class, 'storeDesign'])->name('order-managements.store-design');
    
    Route::put('/order-managements/{order}/shipping-code', [OrderController::class, 'saveShippingCode'])->name('order-managements.shipping-code');
    Route::put('/order-managements/{order}/claim-margin', [OrderController::class, 'claimMargin'])->name('order-managements.claim-margin');

    ////////////// ORDER INVOICES ///////////////
    Route::post('/order-invoice/{order}', [OrderInvoiceController::class, 'create'])->name('order-invoice.create');

    ////////////// TRANSFER MARGIN ///////////////
    Route::get('/transfer-margin', [TransferMarginController::class, 'index'])->name('transfer-margin.index');

    ////////////// MARGIN CLAIMS ///////////////
    Route::get('/margin-claims', [TransferMarginController::class, 'reseller'])->name('margin-claims.index');
    
    ////////////// MARKETING MATERIALS ///////////////
    Route::resource('marketing-materials', MarketingMaterialController::class);
});

Route::get('/storage-get/{path}', [StorageController::class, 'get'])->name('storage-get');
Route::get('/storage-download/{path}', [StorageController::class, 'download'])->name('storage-download');

app/Models/OrderInvoice.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class OrderInvoice extends Model
{
    use HasFactory;

    const TYPE_DOWN_PAYMENT = 'down-payment';
    const TYPE_FINAL_PAYMENT = 'final-payment';

    const STATUS_PENDING = 'pending';
    const STATUS_PAID = 'paid';
    const STATUS_EXPIRED = 'expired';

    /**
     * @var string
     */
    protected $table = 'order_invoices';

    /**
     * @var array
     */
    protected $fillable = [
        'order_id',
        'type',
        'number',
        'amount',
        'due_date',
        'receipt_path',
        'status',
        'paid_at',
        'payment_receipt_path',
        'payment_code',
    ];

    /**
     * @var array
     */
    protected $casts = [
        'due_date' => 'datetime',
        'paid_at' => 'datetime',
    ];

    /**
     * Get the route key for the model.
     *
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'number';
    }

    /**
     * @return BelongsTo
     */
    public function order()
    {
        return $this->belongsTo(Order::class, 'order_id');
    }

    /**
     * @return string|null
     */
    public function getPaymentReceiptAttribute()
    {
        return $this->payment_receipt_path ? route('storage-download', encrypt($this->payment_receipt_path)) : null;
    }

    /**
     * Generate Order Invoice Number
     * 
     * @return string
     */
    public static function generateNumber()
    {
        return 'INV-' . date('ym') . '-' . date('dH') . '-' . date('i');
    }
}

app/Http/Controllers/OrderInvoiceController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Orders\MarkAsPaidRequest;
use App\Models\Order;
use App\Models\OrderInvoice;
use App\Models\TransferMethod;
use App\Services\Orders\OrderInvoiceService;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Request;
use Illuminate\Support\Facades\View;

class OrderInvoiceController extends Controller
{
	/**
	 * @param Order $order
	 * @return RedirectResponse
	 */
	public function create(Order $order, OrderInvoiceService $service)
	{
		Request::validate(['type' => 'required']);
		$service->createInvoice($order, Request::get('type'));
		return Redirect::route('order-managements.show', $order);
	}

	/**
	 * @param OrderInvoice $invoice
	 * @return Illuminate\Contracts\View\View
	 */
	public function show(OrderInvoice $invoice)
	{
		return View::make(Auth::check() ? 'order-invoice.show' : 'order-invoice.customer', [
			'invoice' => $invoice,
			'banks' => TransferMethod::query()->latest()->limit(3)->get(),
		]);
	}

	/**
	 * @param OrderInvoice $invoice
	 * @return Illuminate\Contracts\View\View
	 */
	public function print(OrderInvoice $invoice)
	{
		return View::make('order-invoice.print', [
			'invoice' => $invoice,
			'banks' => TransferMethod::query()->latest()->limit(3)->get(),
		]);
	}

	/**
	 * @param OrderInvoice $invoice
	 * @return Illuminate\Contracts\View\View
	 */
	public function paid(MarkAsPaidRequest $request, OrderInvoice $invoice, OrderInvoiceService $service)
	{
		$service->paid($invoice, $request);
		return Redirect::back();
	}

	/**
	 * @param OrderInvoice $invoice
	 * @param OrderInvoiceService $service
	 * 
	 * @return RedirectResponse
	 */
	public function reset(OrderInvoice $invoice, OrderInvoiceService $service)
	{
		$service->reset($invoice);
		return Redirect::back();
	}
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/order-invoice/customer.blade.php
<x-layouts.customer>
	<x-slot name="header">Order Invoice</x-slot>
	
	<div class="invoice">
		<div id="invoice-print" class="invoice-print">
			<div class="row">
				<div class="col-lg-12">
					<div class="invoice-title">
						<h2>Faktur {{ ucwords(str_replace('-', ' ', __($invoice->type))) }}</h2>
						<div class="invoice-number">{{ $invoice->number }}</div>
					</div>
					<hr>
					<div class="row">
						<div class="col-md-6">
							<address>
								<strong>Ditagih ke:</strong><br>
								{{ $invoice->order->customer }}<br>
								{{ $invoice->order->address }}<br>
								{{ $invoice->order->wa_number }}
							</address>
						</div>
						<div class="col-md-6 text-md-right">
							@if($invoice->type == 'final-payment')
							<address>
								<strong>Dikirim ke:</strong><br>
								{{ $invoice->order->receiver_name }}<br>
								{{ $invoice->order->shipping_address }}<br>
								{{ $invoice->order->receiver_phone }}
							</address>
							@endif
							<address>
								<strong>Tanggal Pesanan:</strong><br>
								{{ $invoice->order->created_at->format('d F Y') }}<br><br>
							</address>
							@if($invoice->paid_at != null)
							<address>
								<strong>Dibayar pada:</strong><br>
								{{ $invoice->paid_at->format('d F Y') }}<br><br>
							</address>
							@endif
						</div>
					</div>
				</div>
			</div>
			
			<div class="row mt-4">
				<div class="col-md-12">
					<div class="section-title">Deskripsi Permintaan</div>
					<p class="section-lead"></p>
					<div>
						{!! $invoice->order->request_description !!}
					</div>
					<div class="table-responsive">
						<table class="table table-striped table-hover table-md">
							<tbody>
								<tr>
									<th>Item</th>
									<th>Harga</th>
									<th style="width: 1px;">Jumlah</th>
									<th style="width: 5cm;" class="text-center">Total</th>
								</tr>
								<tr>
									<td>Custom Batik</td>
									<td>Rp. {{ number_format($invoice->order->unit_price) }}.-</td>
									<td>{{ $invoice->order->quantity }}</td>
									<td class="text-right text-nowrap">Rp. {{ number_format($invoice->order->total_price) }}.-</td>
								</tr>
							</tbody>
						</table>
					</div>

					<div class="row mt-4">
						<div class="col-lg-8">
							<div class="section-title">Metode Pembayaran</div>
							<p class="section-lead">Silahkan melakukan pembayaran sesuai dengan total yang tertera ke salah satu bank di bawah ini.</p>
							<div class="pl-5 d-flex justify-content-around">
								@foreach ($banks as $bank)
								<address>
									<div class="h6">{{ $bank->bank }}</div>
									<div class="h5 font-weight-bold">{{ $bank->number }}</div>
									<div>{{ $bank->name }}</div>
								</address>
								@endforeach
							</div>
						</div>
						<div class="col-lg-4 text-right">
							<div class="invoice-detail-item">
								<div class="invoice-detail-name">Sub Total</div>
								<div class="invoice-detail-value">Rp. {{ number_format($invoice->order->total_price) }}.-</div>
							</div>
							<div class="invoice-detail-item">
								<div class="invoice-detail-name">{{ ucwords(str_replace('-', ' ', $invoice->type)) }} (50%)</div>
								<div class="invoice-detail-value">Rp. {{ number_format($invoice->order->total_price * 0.5) }}.-</div>
							</div>
							@if($invoice->type == 'final-payment')
							<div class="invoice-detail-item">
								<div class="invoice-detail-name">Biaya Kirim</div>
								<div class="invoice-detail-value">Rp. {{ number_format($invoice->order->delivery_fee) }}.-</div>
							</div>
							@endif
							<div class="invoice-detail-item">
								<div class="invoice-detail-name">Kode Pembayaran</div>
								<div class="invoice-detail-value">Rp. {{ number_format($invoice->payment_code) }}.-</div>
							</div>
							<hr class="mt-2 mb-2">
							<div class="invoice-detail-item">
								<div class="invoice-detail-name">Total</div>
								<div class="invoice-detail-value invoice-detail-value-lg">Rp. {{ number_format($invoice->amount + $invoice->payment_code) }}.-</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<hr>
		<div class="text-md-right">
			<div class="float-lg-left mb-lg-0 mb-3">
				@if($invoice->paid_at == null)
					<button type="button" class="btn btn-success btn-icon icon-left" data-toggle="modal" data-target="#mark-as-paid"><i class="fas fa-credit-card"></i> Tandai Lunas</button>
				@else
					<button type="button" class="btn btn-danger btn-icon icon-left" data-confirm="{{ __('modal.reset-invoice') }}" data-confirm-yes="$('#reset-invoice').submit();"><i class="fa fa-clock"></i> Reset</button>
				@endif
				<a href="{{ route('order-managements.show', $invoice->order) }}" class="btn btn-secondary btn-icon icon-left"><i class="fas fa-chevron-left"></i> Kembali</a>
				@if($invoice->payment_receipt)<a href="{{ $invoice->payment_receipt }}" target="_blank" class="ml-2">Download Bukti Pembayaran</a>@endif
			</div>
			<a href="{{ route('order-invoice.print', $invoice) }}" target="_blank" class="btn btn-warning btn-icon icon-left"><i class="fas fa-print"></i> Print</a>
		</div>
	</div>

	<x-modal id="mark-as-paid" title="Upload Bukti Pembayaran">
		<form action="{{ route('order-invoice.paid', $invoice) }}" method="post" enctype="multipart/form-data">@csrf
			<div class="form-group">
				<label>Bukti Pembayaran</label>
				<input type="file" name="payment_receipt" class="form-control-file">
			</div>
			<div class="form-group text-right">
				<button class="btn btn-success btn-icon icon-left"><i class="fas fa-credit-card"></i> Mark as Paid</button>
			</div>
		</form>
	</x-modal>
</x-layouts.customer>

resources/views/order-invoice/show.blade.php
<x-app-layout>
	<x-slot name="header">Faktur Pesanan</x-slot>
	
	<div class="invoice">
		<div id="invoice-print" class="invoice-print">
			<div class="row">
				<div class="col-lg-12">
					<div class="invoice-title">
						<h2>Faktur {{ ucwords(str_replace('-', ' ', __($invoice->type))) }}</h2>
						<div class="invoice-number">{{ $invoice->number }}</div>
					</div>
					<hr>
					<div class="row">
						<div class="col-md-6">
							<address>
								<strong>Ditagih ke:</strong><br>
								{{ $invoice->order->customer }}<br>
								{{ $invoice->order->address }}<br>
								{{ $invoice->order->wa_number }}
							</address>
						</div>
						<div class="col-md-6 text-md-right">
							@if($invoice->type == 'final-payment')
							<address>
								<strong>Dikirim ke:</strong><br>
								{{ $invoice->order->receiver_name }}<br>
								{{ $invoice->order->shipping_address }}<br>
								{{ $invoice->order->receiver_phone }}
							</address>
							@endif
							<address>
								<strong>Tanggal Pesanan:</strong><br>
								{{ $invoice->order->created_at->format('d F Y') }}<br><br>
							</address>
							@if($invoice->paid_at != null)
							<address>
								<strong>Dibayar pada:</strong><br>
								{{ $invoice->paid_at->format('d F Y') }}<br><br>
							</address>
							@endif
						</div>
					</div>
				</div>
			</div>
			
			<div class="row mt-4">
				<div class="col-md-12">
					<div class="section-title">Deskripsi Permintaan</div>
					<p class="section-lead"></p>
					<div>
						{!! $invoice->order->request_description !!}
					</div>
					<div class="table-responsive">
						<table class="table table-striped table-hover table-md">
							<tbody>
								<tr>
									<th>Item</th>
									<th>Harga</th>
									<th style="width: 1px;">Jumlah</th>
									<th style="width: 5cm;" class="text-center">Total</th>
								</tr>
								<tr>
									<td>Custom Batik</td>
									<td>Rp. {{ number_format($invoice->order->unit_price) }}.-</td>
									<td>{{ $invoice->order->quantity }}</td>
									<td class="text-right text-nowrap">Rp. {{ number_format($invoice->order->total_price) }}.-</td>
								</tr>
							</tbody>
						</table>
					</div>

					<div class="row mt-4">
						<div class="col-lg-8">
							<div class="section-title">Metode Pembayaran</div>
							<p class="section-lead">Silahkan melakukan pembayaran sesuai dengan total yang tertera ke salah satu bank di bawah ini.</p>
							<div class="pl-5 d-flex justify-content-around">
								@foreach ($banks as $bank)
								<address>
									<div class="h6">{{ $bank->bank }}</div>
									<div class="h5 font-weight-bold">{{ $bank->number }}</div>
									<div>{{ $bank->name }}</div>
								</address>
								@endforeach
							</div>
						</div>
						<div class="col-lg-4 text-right">
							<div class="invoice-detail-item">
								<div class="invoice-detail-name">Sub Total</div>
								<div class="invoice-detail-value">Rp. {{ number_format($invoice->order->total_price) }}.-</div>
							</div>
							<div class="invoice-detail-item">
								<div class="invoice-detail-name">{{ ucwords(str_replace('-', ' ', $invoice->type)) }} (50%)</div>
								<div class="invoice-detail-value">Rp. {{ number_format($invoice->order->total_price * 0.5) }}.-</div>
							</div>
							@if($invoice->type == 'final-payment')
							<div class="invoice-detail-item">
								<div class="invoice-detail-name">Biaya Kirim</div>
								<div class="invoice-detail-value">Rp. {{ number_format($invoice->order->delivery_fee) }}.-</div>
							</div>
							@endif
							<div class="invoice-detail-item">
								<div class="invoice-detail-name">Kode Pembayaran</div>
								<div class="invoice-detail-value">Rp. {{ number_format($invoice->payment_code) }}.-</div>
							</div>
							<hr class="mt-2 mb-2">
							<div class="invoice-detail-item">
								<div class="invoice-detail-name">Total</div>
								<div class="invoice-detail-value invoice-detail-value-lg">Rp. {{ number_format($invoice->amount + $invoice->payment_code) }}.-</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<hr>
		<div class="text-md-right">
			<div class="float-lg-left mb-lg-0 mb-3">
				@if($invoice->paid_at == null)
					<button type="button" class="btn btn-success btn-icon icon-left" data-toggle="modal" data-target="#mark-as-paid"><i class="fas fa-credit-card"></i> Tandai Lunas</button>
				@else
					<button type="button" class="btn btn-danger btn-icon icon-left" data-confirm="{{ __('modal.reset-invoice') }}" data-confirm-yes="$('#reset-invoice').submit();"><i class="fa fa-clock"></i> Reset</button>
				@endif
				<a href="{{ route('order-managements.show', $invoice->order) }}" class="btn btn-secondary btn-icon icon-left"><i class="fas fa-chevron-left"></i> Kembali</a>
				@if($invoice->payment_receipt)<a href="{{ $invoice->payment_receipt }}" target="_blank" class="ml-2">Download Bukti Pembayaran</a>@endif
			</div>
			<a href="{{ route('order-invoice.print', $invoice) }}" target="_blank" class="btn btn-warning btn-icon icon-left"><i class="fas fa-print"></i> Print</a>
		</div>
	</div>

	@if($invoice->paid_at != null)
	<form id="reset-invoice" action="{{ route('order-invoice.reset', $invoice) }}" class="hidden" method="post">@csrf @method('put')</form>
	@endif

	<x-modal id="mark-as-paid" title="Upload Bukti Pembayaran">
		<form action="{{ route('order-invoice.paid', $invoice) }}" method="post" enctype="multipart/form-data">@csrf
			<div class="form-group">
				<label>Bukti Pembayaran</label>
				<input type="file" name="payment_receipt" class="form-control-file">
			</div>
			<div class="form-group text-right">
				<button class="btn btn-success btn-icon icon-left"><i class="fas fa-credit-card"></i> Tandai Lunas</button>
			</div>
		</form>
	</x-modal>
</x-app-layout>